// Blog Posts Data
export const blogPosts = [
    {
      id: 1,
      date: "2024-11-29",
      author: "Ben Jarman",
      title: "Remembering Fishmongers Hall",
      subtitle: "Five years on",
      category: "POSTS",
      description: "Reflections on and remembrance of the 2019 London Bridge attack",
      image: "/img/blog1.jpg",
    },
    {
      id: 2,
      date: "2024-11-27",
      author: "Ben Jarman",
      title: "Welcome to my new academic homepage",
      subtitle: "",
      category: "NEWS",
      description: "Announcing the launch of benjarman.uk",
      image: "/img/blog2.jpg",
    },
    {
      id: 3,
      date: "2024-11-25",
      author: "Ben Jarman",
      title: "Exploring Parole Decisions",
      subtitle: "An in-depth analysis",
      category: "RESEARCH",
      description: "A look at how parole decisions are made and their broader implications.",
      image: "/img/blog3.jpg",
    },
    {
      id: 4,
      date: "2024-11-20",
      author: "Ben Jarman",
      title: "Life Behind Bars",
      subtitle: "Human stories of resilience",
      category: "POSTS",
      description: "Sharing stories of resilience and survival from life in prison.",
      image: "/img/blog4.jpg",
    },
    {
      id: 5,
      date: "2024-11-15",
      author: "Ben Jarman",
      title: "Reflections on Justice Systems",
      subtitle: "Learning from the past",
      category: "NEWS",
      description: "An overview of reforms and challenges within the justice system.",
      image: "/img/blog5.jpg",
    },
    {
      id: 6,
      date: "2024-11-10",
      author: "Ben Jarman",
      title: "Academic Research 2024",
      subtitle: "Key findings and conclusions",
      category: "RESEARCH",
      description: "Summarizing key academic research findings from 2024.",
      image: "/img/blog6.jpg",
    },
    {
      id: 7,
      date: "2024-11-05",
      author: "Ben Jarman",
      title: "The Role of Rehabilitation",
      subtitle: "A policy perspective",
      category: "POSTS",
      description: "Why rehabilitation matters in modern criminal justice systems.",
      image: "/img/blog7.jpg",
    },
    {
      id: 8,
      date: "2024-11-01",
      author: "Ben Jarman",
      title: "Prison Reform in the UK",
      subtitle: "Progress and setbacks",
      category: "NEWS",
      description: "A detailed analysis of recent prison reforms and their outcomes.",
      image: "/img/blog8.jpg",
    },
    {
      id: 9,
      date: "2024-10-29",
      author: "Ben Jarman",
      title: "Researching Life Sentences",
      subtitle: "",
      category: "RESEARCH",
      description: "An exploration of the realities of life sentences in the UK.",
      image: "/img/blog9.jpg",
    },
    {
      id: 10,
      date: "2024-10-25",
      author: "Ben Jarman",
      title: "Reflections on Prison Education",
      subtitle: "Empowering change",
      category: "POSTS",
      description: "How education in prisons can pave the way for transformation.",
      image: "/img/blog10.jpg",
    },
    {
      id: 11,
      date: "2024-10-20",
      author: "Ben Jarman",
      title: "Parole and Public Perception",
      subtitle: "Bridging the gap",
      category: "NEWS",
      description: "How public perception influences parole policies and decisions.",
      image: "/img/blog11.jpg",
    },
    {
      id: 12,
      date: "2024-10-15",
      author: "Ben Jarman",
      title: "Writing for Justice",
      subtitle: "Stories from the inside",
      category: "POSTS",
      description: "Highlighting the voices of prisoners through writing programs.",
      image: "/img/blog12.jpg",
    },
    {
      id: 13,
      date: "2024-10-10",
      author: "Ben Jarman",
      title: "Impact of Sentencing Policies",
      subtitle: "",
      category: "RESEARCH",
      description: "Analyzing the long-term impact of sentencing policies in the UK.",
      image: "/img/blog13.jpg",
    },
    {
      id: 14,
      date: "2024-10-05",
      author: "Ben Jarman",
      title: "Prisoner Welfare Initiatives",
      subtitle: "Looking forward",
      category: "NEWS",
      description: "Innovative welfare initiatives for prisoners' mental health.",
      image: "/img/blog14.jpg",
    },
    {
      id: 15,
      date: "2024-10-01",
      author: "Ben Jarman",
      title: "Building Networks for Research",
      subtitle: "Collaboration matters",
      category: "RESEARCH",
      description: "The importance of building collaborative research networks.",
      image: "/img/blog15.jpg",
    },
  ];
  
  // Blog Categories
  export const blogCategories = [
    { id: "all", name: "All", count: 22 },
    { id: "changing-inside", name: "changing inside", count: 20 },
    { id: "news", name: "news", count: 6 },
    { id: "posts", name: "posts", count: 21 },
    { id: "reading-note", name: "reading note", count: 6 },
    { id: "research-log", name: "research log", count: 9 },
  ];
  
  // Blog Note Content
  export const blogNote = {
    title: "Note",
    description: `This page shows news items and blog posts from past and current projects. 
    The ‘changing inside’ category shows content originally published at the `,
    link: {
      url: "#",
      text: "Changing Inside",
    },
  };
  
  // Blog Sorting Options
  export const sortOptions = [
    { value: "latest", label: "Latest" },
    { value: "oldest", label: "Oldest" },
    { value: "popular", label: "Most Popular" },
  ];
  